<h1>About Me</h1>
<p>
    I'm a web developer. <br /><br />
    My name is {{ this.$parent.name }}. <br />
    <button v-on:click="this.$parent.hit">Click this as a proof</button>
</p>

<script type="application/javascript">
    let name = `{{ this.$parent.name }}`
</script>

<?php $this->inlineScript()->prependFile('/js/about.js', 'module'); ?>
<script type="module">
import About from '/js/about.js';
About(name).showoff();
</script>